Fix : Typos in README.md #5
cn10xdev/ECommerce_Product_Page pull request #15
Opened 2024-09-22 15:25 UTC by Prity25-coder

Fixed all the typos.
This PR will close #5

2024-09-23 11:31 UTC, Ezio-Sarthak requested changes
Thanks for working on this @Prity25-coder . I've added some comments 👍

2024-09-23 11:31 UTC, Ezio-Sarthak commented on README.md
> +    npm run start
`npm start` also works for me. maybe we can create an `or` here for understanding purpose

2024-09-23 11:31 UTC, Ezio-Sarthak commented on README.md
> +11. Create a `Pull-Request` to the main branch(main branch of the original repo) from your forked repo branch
a space b/w branch and `(` would look clean 👍

2024-09-23 11:31 UTC, Ezio-Sarthak commented on README.md
> +|-- .gitignore               # To ignore the files and folders from git
can we use an underscore here instead of hyphen to align with the rest of the chart?

2024-09-23 17:47 UTC, Prity25-coder commented on README.md
> +    npm run start
Addressed

2024-09-23 17:48 UTC, Prity25-coder commented on README.md
> +11. Create a `Pull-Request` to the main branch(main branch of the original repo) from your forked repo branch
Addressed

2024-09-23 17:48 UTC, Prity25-coder commented on README.md
> +|-- .gitignore               # To ignore the files and folders from git
Addressed

2024-09-24 11:17 UTC, Ezio-Sarthak approved these changes
Thanks for updating the PR @Prity25-coder !

This looks good to go! Approving this 👍

2024-09-24 17:30 UTC, Prity25-coder commented
Conflict resolved.

2024-09-24 18:06 UTC, Prity25-coder commented
Closing this PR, because some un-necessary commits are there.

- Raised another PR with same changes #42

2024-09-24 18:06 UTC, closed without merging

2024-09-28 12:51 UTC, Ezio-Sarthak commented
@Prity25-coder as mentioned earlier, kindly update the same PR by deleting those commits, please refrain from closing PRs. It will be difficult to track progress in those cases.